### ISSUE TITLE
Parse Error:  line 1890, file "ical.js

### ISSUE THREAD

**Issue by MJGPreHea** [derekantrican/GAS-ICS-Sync#108]
When running the script there is an error with parsing data from external calendar file

Error Code
ParserError: invalid line (no token ";" or ":") "Jane Doe" (line 1890, file "ical.js")

Log Text
[20-03-11 15:02:54:725 PDT] Syncing 1 calendars to https://www.halaxy.com/a/calendar/mj2z21p/oi4u1zi6co/halaxy.ical
[20-03-11 15:02:54:839 PDT] Working on calendar: 3s751ivsmjlocstqtful5l0i53ju8msd@import.calendar.google.com
[20-03-11 15:02:54:925 PDT] Fetched 0 existing events from https://www.halaxy.com/a/calendar/mj2z21p/oi4u1zi6co/halaxy.ical
[20-03-11 15:02:54:939 PDT] ParserError: invalid line (no token ";" or ":") "Jane Doe"
    at ICAL.parse.parser._handleContentLine(ical.js:1890:7)
    at [unknown function](ical.js:1732:14)
    at ICAL.parse.parser._eachLine(ical.js:2191:11)
    at parser(ical.js:1731:12)
    at parseResponses(Helpers:106:25)
    at startSync(Code:164:17)

Line 22 in Code.gs
iCal URL ["https://www.halaxy.com/a/calendar/mj2z21p/oi4u1zi6co/halaxy.ical", "https://www.halaxy.com/a/calendar/mj2z21p/oi4u1zi6co/halaxy.ical"]

**Comment by derekantrican** [comment]
It looks like this might be the problem:

`DESCRIPTION:Patients\: \nJane Doe\n\nNote\:\n`

Not sure why a colon would need to be escaped

**Comment by derekantrican** [comment]
@MJGPreHea did you have any info to add to my questions?
