### ISSUE TITLE
Dealing with short DTSTART for All-Day-Events

### ISSUE THREAD

**Issue by Dunstkreis** [derekantrican/GAS-ICS-Sync#229]
I have got a .ics Export from a platform that uses "DTSTART:20210822" for all day events.
Google just imports those fine so it would be nice to mimic this behavior.

I am getting this stack trace:
```
Error: invalid date-time value: "2021-08-22T::"
    at ICAL.Time.fromDateTimeString(ical.js:5900:13)
    at decorate(ical.js:781:28)
    at _decorate(ical.js:2938:47)
    at _hydrateValue(ical.js:2921:44)
    at getFirstValue(ical.js:3067:19)
    at getFirstPropertyValue(ical.js:2499:21)
    at _firstProp(ical.js:9330:29)
    at get startDate(ical.js:9146:19)
    at createEvent(Helpers:266:16)
    at processEvent(Helpers:197:18)
```

So I just fiddled with the code and added a "String-extension" if it matches the pattern above.

Don't know if its the best place to put it or if this is wanted at all, hence this feature request to discuss it.

**Comment by Dunstkreis** [comment]
Didnt know about strict mode. Solves it.
-closed-
