### ISSUE TITLE
Sync Failure with Attachments

### ISSUE THREAD

**Issue by cjam28** [derekantrican/GAS-ICS-Sync#415]
### The problem

When a google doc link is included in the ICS invite it fails to sync due to a missing parameter value:

ParserError: Missing parameter value in 'ATTACH;FILENAME=Notes Document;FMTTYPE=application/vnd.google-apps.document;https://docs.google.com/document/d/DOC_ID_Removed_For_Privacy/editATTACH;FILENAME=Notes Document;FMTTYPE=application/vnd.google-apps.document;https://docs.google.com/document/d/DOC_ID_Removed_For_Privacy/edit?usp=sharing'
    at ICAL.parse.parser._handleContentLine(ical.js:1894:9)
    at [unknown function](ical.js:1770:14)
    at ICAL.parse.parser._eachLine(ical.js:2243:11)
    at parser(ical.js:1769:12)
    at parseResponses(Helpers:209:25)
    at startSync(Code:207:17)

### Version of GAS-ICS-Sync

5.8

**Comment by jonas0b1011001** [comment]
#351
